### ISSUE TITLE
error Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by chocolatemetoprolol** [xughv/certificate-minapp#1]
Cannot read property 'data' of undefined;at pages/categorys/categorys onLoad function;at api request fail callback function
TypeError: Cannot read property 'data' of undefined
    at Function.fail (http://127.0.0.1:9973/appservice/utils/request.js:29:47)
    at Object.fail (

 后台的数据格式 能否告知  自己好在本地 搭建一个 谢谢 你的这个 似乎访问不到 谢谢

**Comment by xughv** [comment]
可以参考下 [xughv/cert](https://github.com/xughv/cert)

```
返回格式
{
    code: 0,
    data: (JSON 数据)
}
```

[Category]:
```
_id: {
	type: Schema.Types.ObjectId,
},
name: {
	type: String,
}
```

[Chapter]:
```
_id: {
	type: Schema.Types.ObjectId,
},
name: {
	type: String,
},
categoryId: {
	type: Schema.Types.ObjectId,
},
```

[Problem]:
```
_id: {
	type: Schema.Types.ObjectId,
},
chapterId: {
	type: Schema.Types.ObjectId,
},
problem: {
	type: String,
},
choices: {
	type: Schema.Types.Mixed,
},
answer: {
	type: [String],
},
analysis: {
	type: String,
}
```

**Comment by xughv** [comment]
![image](https://user-images.githubusercontent.com/14882240/31871750-53f956f8-b77c-11e7-8179-754ca15abbb8.png)

![image](https://user-images.githubusercontent.com/14882240/31871755-5ef4e996-b77c-11e7-821f-e05b26d2f9af.png)

![image](https://user-images.githubusercontent.com/14882240/31871734-42e4b07e-b77c-11e7-82bc-507d6ce06a6b.png)

不好意思，项目好久没有维护过，数据落地在 mongo，不知道有没有帮助 ~

**Comment by chocolatemetoprolol** [comment]
谢谢
